# Generated by Django 4.2 on 2023-04-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vLogradouro', models.CharField(max_length=80)),
                ('vComplemento', models.CharField(max_length=50)),
                ('vBairro', models.CharField(max_length=40)),
                ('vNumero', models.CharField(max_length=10)),
                ('cUF', models.CharField(max_length=2)),
            ],
        ),
    ]
