# Generated by Django 4.2 on 2023-04-23 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0004_alter_endereco_cuf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cUF',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='O campo cUF deve ter exatamente dois caracteres maiúsculos.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='vNumero',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Somente números são permitidos.', regex='^[0-9]*$')]),
        ),
    ]
