# Generated by Django 4.2 on 2023-04-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vDesc_veiculo', models.CharField(max_length=35)),
                ('vPlaca', models.CharField(max_length=7)),
                ('nValor', models.DecimalField(decimal_places=3, max_digits=15)),
                ('iCod_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
