# Generated by Django 4.2 on 2023-04-23 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='vPlaca',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='A placa deve seguir o formato LLLNLNN.', regex='^[A-Z]{3}\\d[A-Z0-9]{2}\\d$')]),
        ),
    ]
