# Generated by Django 4.2 on 2023-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_alter_veiculo_vplaca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='nValor',
            field=models.DecimalField(decimal_places=3, error_messages={'invalid': 'Por favor, insira um número válido.'}, max_digits=15),
        ),
    ]
