# Generated by Django 4.2 on 2023-04-23 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_veiculo_nvalor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='nValor',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.RegexValidator(message='Por favor, insira apenas números.', regex='^\\d+$')]),
        ),
    ]
