# Generated by Django 4.2 on 2023-04-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vNome_fantasia', models.CharField(max_length=80)),
                ('vNome_razao_social', models.CharField(max_length=80)),
                ('vCnpj', models.CharField(max_length=14)),
                ('vEmail', models.CharField(max_length=40)),
                ('vObservacao', models.CharField(max_length=200)),
                ('iCod_endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
