# Generated by Django 4.2 on 2023-04-23 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_vcnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='vEmail',
            field=models.CharField(max_length=40, validators=[django.core.validators.EmailValidator(message='Digite um email válido.')]),
        ),
    ]
